### ISSUE TITLE
edit structure does not get stored in xyz file

### ISSUE THREAD

**Issue by klauspdoll** [molpro/iMolpro#203] opened 2024-01-19 09:43 UTC
I create a new project bla3.molpro,  no structure imported ("No" , "Cancel")

Input is the default one:

```
geometry=bla3.xyz
basis=cc-pV(T+d)Z-PP
df-rhf

```

initial bla3.xyz is:

```
1

C 0.0 0.0 0.0

```

Now Edit/Structure and replace the "C" there with H2O. The xyz file is still the same, not H2O. When I run, it runs with a carbon atom as geometry.

**Comment by pjknowles** [comment] 2024-01-19 09:52
Duplicate of #30

**Closed as completed by pjknowles** 2024-01-19 09:52 UTC
