### ISSUE TITLE
upon startup: SyntaxWarning: invalid escape sequence '\w'

### ISSUE THREAD

**Issue by klauspdoll** [molpro/iMolpro#187] opened 2024-01-11 09:28 UTC
version 5c2f086051472  yet non-reproducible

after startup:

```
iMolpro/molpro_input.py:586: SyntaxWarning: invalid escape sequence '\w'
  if line.strip() and line.strip()[0] != '{' and not re.match('^ *\w+ *=', line) and not in_group:

```

I have seen it twice, but cannot reproduce it now.

**Comment by pjknowles** [comment] 2024-01-11 09:52
I can't reproduce this. It would be enough to provide an input that causes it. But I suspect that  it is fixed by making the pattern a raw string.

**Comment by klauspdoll** [comment] 2024-01-11 15:54
I tried all possible inputs, to no avail.

Then I did 

git pull

and just started iMolpro     (no project opened, only the splash screen !!!):

`python iMolpro.py &`
(nothing else done!)
```
[1] 5548
molpro_input.py:591: SyntaxWarning: invalid escape sequence '\w'
  if line.strip() and line.strip()[0] != '{' and not re.match('^ *\w+ *=', line) and not in_group:

```

**Comment by pjknowles** [comment] 2024-01-11 16:19
Yes, I agree, and I thought it was fixed in #189 .

**Closed as completed** 2024-01-11 17:19 UTC
